import React, { useState, useEffect, useRef } from 'react';
import { GoldenRecordCase } from '../../lib/types/funeral';
import { 
  X, 
  Play, 
  Pause, 
  RotateCcw, 
  CheckCircle2, 
  ChevronRight, 
  Layers, 
  ShieldCheck, 
  Truck, 
  ScrollText, 
  FileCheck, 
  Receipt, 
  CreditCard, 
  Building2, 
  Printer, 
  Video, 
  Sparkles, 
  ExternalLink, 
  Copy, 
  Check, 
  Clock, 
  Terminal,
  Zap,
  ArrowRight
} from 'lucide-react';

import { issueBurialTransitPermit, generateNycDohXmlPayload } from '../../lib/services/edrsVitalService';
import { generateQBOInvoiceFromCase, generateVendorBillsForCase } from '../../lib/services/quickbooksService';
import { generateSplitPayCrowdfundLink } from '../../lib/services/stripePaymentService';
import { generateLiveStreamCredentials } from '../../lib/services/webcastGatewayService';
import { runPreflightInspection } from '../../lib/services/commercialPressService';

export interface SimulationStep {
  id: number;
  title: string;
  phase: 'Phase 1: Intake & Custody' | 'Phase 2: Legal & Financial' | 'Phase 3: Regulatory & Press' | 'Phase 4: Broadcast & Service' | 'Phase 5: Golden Archive';
  statutoryLabel: string;
  icon: React.ElementType;
  colorClass: string;
  summary: string;
  payloadType: string;
  getPayload: (c: GoldenRecordCase) => string;
  launchKey: string;
  systemConnected: string;
}

interface CaseLifecycleSimulatorModalProps {
  isOpen: boolean;
  onClose: () => void;
  activeCase: GoldenRecordCase;
  cases: GoldenRecordCase[];
  onSelectCase?: (c: GoldenRecordCase) => void;
  onAdvancePhase?: (caseId: string, nextPhase: any) => void;
  onLaunchModal?: (modalKey: string, targetCase: GoldenRecordCase) => void;
}

export const CaseLifecycleSimulatorModal: React.FC<CaseLifecycleSimulatorModalProps> = ({
  isOpen,
  onClose,
  activeCase: initialCase,
  cases,
  onSelectCase,
  onAdvancePhase,
  onLaunchModal
}) => {
  const [currentCase, setCurrentCase] = useState<GoldenRecordCase>(initialCase || cases[0]);
  const [currentStepIndex, setCurrentStepIndex] = useState<number>(0);
  const [isPlaying, setIsPlaying] = useState<boolean>(false);
  const [completedSteps, setCompletedSteps] = useState<number[]>([]);
  const [logs, setLogs] = useState<string[]>([]);
  const [copiedPayload, setCopiedPayload] = useState<boolean>(false);
  const autoPlayTimerRef = useRef<any>(null);

  useEffect(() => {
    if (initialCase) {
      setCurrentCase(initialCase);
    }
  }, [initialCase]);

  const steps: SimulationStep[] = [
    {
      id: 1,
      title: 'First Call Intake & Vehicle Livery Dispatch',
      phase: 'Phase 1: Intake & Custody',
      statutoryLabel: 'NYS PHL § 4201 Custody Affidavit • Twilio Cellular SMS',
      icon: Truck,
      colorClass: 'text-blue-700 bg-blue-50 border-blue-300',
      summary: `First Call logged from ${currentCase?.decedent?.placeOfDeath || 'Mount Sinai Morningside'}. Driver James Wilson dispatched via Twilio SMS. Chain-of-custody transfer confirmed.`,
      payloadType: 'SMS Livery Dispatch Packet',
      getPayload: (c) => JSON.stringify({
        dispatchId: `DISPATCH-LIV-${c.caseNumber}`,
        driverName: 'James Wilson (Lead Livery Transport)',
        pickupLocation: c.decedent?.placeOfDeath || 'Mount Sinai Morningside (Harlem, NY)',
        destination: "Benta's Funeral Home, Inc. (630 St Nicholas Ave)",
        vehicleAssigned: 'Cadillac Commercial Lead Coach #11',
        chainOfCustodyStatus: 'SECURED_IN_TRANSIT',
        twilioSmsSid: 'SM992841029348102948102948'
      }, null, 2),
      launchKey: 'removal',
      systemConnected: 'Twilio Cellular SMS Gateway (+1 313-631-3704)'
    },
    {
      id: 2,
      title: 'Arrangement Conference & AI Obituary Suite',
      phase: 'Phase 1: Intake & Custody',
      statutoryLabel: 'Form AP-47 Statutory Selection • GPT-4o 9-Part Obituary',
      icon: ScrollText,
      colorClass: 'text-indigo-700 bg-indigo-50 border-indigo-300',
      summary: 'Family arrangement conference completed. 9-Part bespoke obituary generated by OpenAI GPT-4o with cultural Harlem heritage reverence.',
      payloadType: 'AI Obituary Draft & Case Selections',
      getPayload: (c) => JSON.stringify({
        caseNumber: c.caseNumber,
        decedent: c.decedent.legalName,
        selectedPackage: c.dispositionType.toUpperCase(),
        obituaryStyle: 'Celebration of Life & Faith',
        generatedParagraph: `${c.decedent.legalName}, a beloved pillar of the Harlem community, transitioned gracefully into eternal rest...`,
        aiTokensProcessed: 1420,
        model: 'GPT-4o-2026-Omni'
      }, null, 2),
      launchKey: 'ai',
      systemConnected: 'OpenAI GPT-4o & Whisper Voice Engine'
    },
    {
      id: 3,
      title: 'DocuSign NYS ESRA Legal E-Signatures',
      phase: 'Phase 2: Legal & Financial',
      statutoryLabel: 'NYS PHL § 4201 Affidavit • NYS ESRA § 304 Compliant',
      icon: FileCheck,
      colorClass: 'text-amber-700 bg-amber-50 border-amber-300',
      summary: 'Legal envelope dispatched via DocuSign with SMS OTP identity verification. Form AP-47 and Right-to-Control affidavits fully executed.',
      payloadType: 'DocuSign Envelope Manifest',
      getPayload: (c) => JSON.stringify({
        envelopeId: `2c1ecd41-421c-4fce-a8a7-a9b5a8c92fd0`,
        signerName: c.informant?.fullName || 'Regina Cross',
        signerPhone: c.informant?.phone || '(212) 555-0192',
        documentsSigned: [
          'NYS PHL § 4201 Right to Control Disposition Affidavit',
          'Benta Form AP-47 Statement of Goods and Services',
          'Woodlawn Crematory Authorization (Bronx, NY)'
        ],
        smsOtpAuthVerified: true,
        certificateOfCompletionUrl: 'https://docusign.net/verify/bfh-2026-08850'
      }, null, 2),
      launchKey: 'docusign',
      systemConnected: 'DocuSign Developer / Production Gateway'
    },
    {
      id: 4,
      title: 'QuickBooks Online 2-Way GL & AP-47 Invoicing',
      phase: 'Phase 2: Legal & Financial',
      statutoryLabel: 'GAAP Double-Entry Ledger • Form AP-47 Sync • 1099 Bills',
      icon: Receipt,
      colorClass: 'text-teal-700 bg-teal-50 border-teal-300',
      summary: 'Two-way sync generated Customer Invoice in Intuit QuickBooks Online matching Form AP-47. 1099 vendor disbursements scheduled.',
      payloadType: 'QBO Invoice & Double-Entry Journal',
      getPayload: (c) => {
        const inv = generateQBOInvoiceFromCase(c);
        const bills = generateVendorBillsForCase(c);
        return JSON.stringify({
          qboRealmId: '9341452938102914',
          invoiceNumber: inv.qboDocNumber,
          totalAmount: `$${inv.totalAmount.toLocaleString()}`,
          vendorBillsCreated: bills.length,
          generalLedgerDebitsCredits: `$${inv.totalAmount.toLocaleString()}`,
          syncStatus: 'SYNCED_WITH_INTUIT_QBO'
        }, null, 2);
      },
      launchKey: 'quickbooks',
      systemConnected: 'Intuit QuickBooks Online REST API'
    },
    {
      id: 5,
      title: 'Stripe Merchant Split-Pay & ACH Checkout',
      phase: 'Phase 2: Legal & Financial',
      statutoryLabel: 'PCI-DSS Level 1 • Apple Pay • Plaid ACH Bank Debit',
      icon: CreditCard,
      colorClass: 'text-emerald-700 bg-emerald-50 border-emerald-300',
      summary: 'Split-Pay crowdfunding checkout link generated. $4,500 initial family deposit settled via Stripe Apple Pay with instant ledger posting.',
      payloadType: 'Stripe Transaction & Split-Pay Manifest',
      getPayload: (c) => JSON.stringify({
        chargeId: `ch_3MtwL2LkdIwHu7ix0B20260${c.caseNumber.slice(-3)}`,
        amount: '$4,500.00',
        paymentMethod: 'Apple Pay (Visa •••• 4242)',
        splitPayShareableLink: generateSplitPayCrowdfundLink(c.caseNumber),
        payoutDestination: 'JPMorgan Chase (Benta Operating •••• 8850)',
        status: 'succeeded'
      }, null, 2),
      launchKey: 'stripe',
      systemConnected: 'Stripe Merchant Gateway & Webhook Engine'
    },
    {
      id: 6,
      title: 'NYC DOHMH eVital / EDRS & 72-Hr Transit Permit',
      phase: 'Phase 3: Regulatory & Press',
      statutoryLabel: '10 NYCRR § 77.8 • NYC Health Code § 205.25 • Form V-11',
      icon: Building2,
      colorClass: 'text-red-800 bg-red-50 border-red-300',
      summary: '36-field statutory matrix submitted to NYC DOHMH Bureau of Vital Statistics. State File number registered and 72-Hour Transit Permit issued.',
      payloadType: 'NYC DOHMH eVital XML Payload',
      getPayload: (c) => {
        const permit = issueBurialTransitPermit(c);
        return `<!-- NYC DOHMH eVital Payload (State File #${permit.stateFileNumber}) -->\n` + generateNycDohXmlPayload(c);
      },
      launchKey: 'edrs',
      systemConnected: 'NYC DOHMH eVital & NYS Health Commerce System'
    },
    {
      id: 7,
      title: 'Harlem Heritage Commercial Press & 300 DPI Preflight',
      phase: 'Phase 3: Regulatory & Press',
      statutoryLabel: '300 DPI CMYK PDF/X-1a Preflight • 4-Hr Rush Courier',
      icon: Printer,
      colorClass: 'text-amber-800 bg-amber-50 border-amber-300',
      summary: 'Automated preflight validated 300 DPI CMYK resolution, bleed margins, and embedded fonts. Job ticket dispatched via secure SFTP.',
      payloadType: 'Press Preflight & Job Ticket',
      getPayload: (c) => {
        const preflight = runPreflightInspection(c, '4_panel_bulletin');
        return JSON.stringify({
          jobTicketId: `PRESS-2026-HH-${c.caseNumber}`,
          partner: 'Harlem Heritage Commercial Print Guild (125th St)',
          preflightPassed: preflight.passed,
          resolutionDPI: preflight.resolutionDPI,
          colorSpace: preflight.colorSpace,
          quantity: 250,
          turnaroundTier: '4-Hour Same-Day VIP Courier',
          deliveryAddress: "Benta's Funeral Home, Inc. (630 St Nicholas Ave)"
        }, null, 2);
      },
      launchKey: 'press',
      systemConnected: 'Harlem Heritage Press SFTP / API Gateway'
    },
    {
      id: 8,
      title: 'Live 4K Sanctuary Webcasting & Security PIN',
      phase: 'Phase 4: Broadcast & Service',
      statutoryLabel: '4K HLS Low-Latency Stream • PIN Protected Family Portal',
      icon: Video,
      colorClass: 'text-purple-700 bg-purple-50 border-purple-300',
      summary: 'Chapel 1 PTZ multi-camera studio activated. Live 4K HLS stream running with secure family PIN validation (#8921) for remote mourners worldwide.',
      payloadType: '4K Webcast Credentials & Active Telemetry',
      getPayload: (c) => {
        const creds = generateLiveStreamCredentials(c.caseNumber);
        return JSON.stringify({
          streamUrl: creds.streamUrl,
          securityPin: creds.securityPin,
          embedCode: creds.embedCode,
          activeViewers: 47,
          remoteCondolencesLogged: 18,
          hlsStatus: 'LIVE_BROADCASTING'
        }, null, 2);
      },
      launchKey: 'webcast',
      systemConnected: 'Vimeo Enterprise Live Streaming & OneRoom'
    },
    {
      id: 9,
      title: 'VIP Day-of-Service HUD & S3 Golden Vault Archival',
      phase: 'Phase 5: Golden Archive',
      statutoryLabel: 'Zero Data Loss Protocol • 256-Bit AES Golden Record Vault',
      icon: Sparkles,
      colorClass: 'text-emerald-800 bg-emerald-50 border-emerald-300',
      summary: 'Service executed with precision. All photos, signed contracts, audio archives, and death records sealed into the S3 Golden Vault.',
      payloadType: 'Golden Record Archive Manifest',
      getPayload: (c) => JSON.stringify({
        caseNumber: c.caseNumber,
        decedent: c.decedent.legalName,
        totalDocumentsArchived: 14,
        totalMediaAssetsSecured: 28,
        storageBucket: 'bfh-golden-vault-production',
        sha256Seal: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        lifecycleStatus: 'PERMANENTLY_SEALED_COMPLETED'
      }, null, 2),
      launchKey: 'golden_record',
      systemConnected: 'Supabase Postgres & AWS S3 Golden Vault'
    }
  ];

  const currentStep = steps[currentStepIndex];

  const advanceStep = (nextIdx: number) => {
    if (nextIdx >= steps.length) {
      setIsPlaying(false);
      setLogs(prev => [
        `[${new Date().toLocaleTimeString()}] 🎉 Complete Case Lifecycle Executed Successfully (100% Statutory Compliance)!`,
        ...prev
      ]);
      return;
    }

    setCurrentStepIndex(nextIdx);
    setCompletedSteps(prev => Array.from(new Set([...prev, nextIdx])));
    
    const stepObj = steps[nextIdx];
    setLogs(prev => [
      `[${new Date().toLocaleTimeString()}] ✔ Step ${stepObj.id} Executed: ${stepObj.title} [${stepObj.systemConnected}]`,
      ...prev
    ]);

    // Advance phase on case if applicable
    if (nextIdx === 2) onAdvancePhase?.(currentCase.id, 'arrangement');
    else if (nextIdx === 5) onAdvancePhase?.(currentCase.id, 'regulatory_legal');
    else if (nextIdx === 7) onAdvancePhase?.(currentCase.id, 'production_prep');
    else if (nextIdx === 8) onAdvancePhase?.(currentCase.id, 'completed');
  };

  const handleToggleAutoPlay = () => {
    if (isPlaying) {
      setIsPlaying(false);
      if (autoPlayTimerRef.current) clearInterval(autoPlayTimerRef.current);
    } else {
      setIsPlaying(true);
      if (completedSteps.length === steps.length) {
        setCompletedSteps([0]);
        setCurrentStepIndex(0);
      }
    }
  };

  useEffect(() => {
    if (isPlaying) {
      autoPlayTimerRef.current = setInterval(() => {
        setCurrentStepIndex(prev => {
          const next = prev + 1;
          if (next >= steps.length) {
            setIsPlaying(false);
            clearInterval(autoPlayTimerRef.current);
            return prev;
          }
          setCompletedSteps(c => Array.from(new Set([...c, next])));
          const stepObj = steps[next];
          setLogs(l => [
            `[${new Date().toLocaleTimeString()}] ✔ Step ${stepObj.id} Executed: ${stepObj.title} [${stepObj.systemConnected}]`,
            ...l
          ]);
          return next;
        });
      }, 2400);
    } else {
      if (autoPlayTimerRef.current) clearInterval(autoPlayTimerRef.current);
    }

    return () => {
      if (autoPlayTimerRef.current) clearInterval(autoPlayTimerRef.current);
    };
  }, [isPlaying, steps.length]);

  const handleReset = () => {
    setIsPlaying(false);
    if (autoPlayTimerRef.current) clearInterval(autoPlayTimerRef.current);
    setCurrentStepIndex(0);
    setCompletedSteps([0]);
    setLogs([`[${new Date().toLocaleTimeString()}] Simulation reset to Step 1 (Intake).`]);
  };

  const copyPayload = () => {
    if (!currentStep) return;
    navigator.clipboard.writeText(currentStep.getPayload(currentCase));
    setCopiedPayload(true);
    setTimeout(() => setCopiedPayload(false), 2000);
  };

  if (!isOpen) return null;

  const progressPercent = Math.round(((completedSteps.length) / steps.length) * 100);

  return (
    <div className="fixed inset-0 z-50 bg-black/85 backdrop-blur-md flex items-center justify-center p-3 sm:p-5 overflow-y-auto animate-fadeIn">
      <div className="bg-[#fcfbfa] border border-neutral-300 rounded-3xl max-w-6xl w-full max-h-[94vh] flex flex-col shadow-2xl text-neutral-900 overflow-hidden">
        
        {/* HEADER */}
        <div className="p-5 sm:p-6 bg-white border-b border-neutral-200 flex flex-wrap items-center justify-between gap-4 shrink-0">
          <div className="flex items-center space-x-3.5">
            <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-red-900 via-amber-800 to-neutral-900 flex items-center justify-center shadow-lg shadow-red-950/20 border border-amber-400/50">
              <Sparkles className="w-6 h-6 text-amber-300 animate-pulse" />
            </div>
            <div>
              <div className="flex items-center space-x-2.5">
                <h2 className="font-serif-title text-xl font-bold text-neutral-900">
                  End-to-End Case Lifecycle Simulation Runner
                </h2>
                <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-amber-50 text-amber-950 border border-amber-300 flex items-center gap-1 shadow-2xs">
                  <Zap className="w-3.5 h-3.5 text-amber-700" />
                  Full 5-Phase Automated Tour
                </span>
              </div>
              <p className="text-xs text-neutral-600 font-light mt-0.5">
                Simulates the entire statutory and commercial progression across all 9 connected enterprise systems.
              </p>
            </div>
          </div>

          <div className="flex items-center space-x-3">
            {/* Case Selector */}
            <select
              value={currentCase.id}
              onChange={(e) => {
                const found = cases.find(c => c.id === e.target.value);
                if (found) {
                  setCurrentCase(found);
                  onSelectCase?.(found);
                }
              }}
              className="px-3 py-1.5 bg-neutral-100 border border-neutral-300 rounded-xl text-xs font-semibold text-neutral-800 outline-none focus:border-amber-600"
            >
              {cases.map(c => (
                <option key={c.id} value={c.id}>
                  Case #{c.caseNumber} - {c.decedent.legalName}
                </option>
              ))}
            </select>

            <button
              onClick={onClose}
              className="p-2 text-neutral-500 hover:text-neutral-900 hover:bg-neutral-100 rounded-full transition cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* CONTROLS & PROGRESS BAR */}
        <div className="bg-[#f7f6f4] px-6 py-4 border-b border-neutral-200 flex flex-wrap items-center justify-between gap-4 shrink-0">
          <div className="flex items-center space-x-3">
            <button
              onClick={handleToggleAutoPlay}
              className={`px-4 py-2 rounded-xl text-xs font-bold flex items-center space-x-2 transition shadow-md border cursor-pointer ${
                isPlaying 
                  ? 'bg-amber-600 hover:bg-amber-700 text-white border-amber-400/50' 
                  : 'bg-[#991b1b] hover:bg-red-800 text-white border-amber-400/40'
              }`}
            >
              {isPlaying ? (
                <>
                  <Pause className="w-3.5 h-3.5 fill-white" />
                  <span>Pause Simulation</span>
                </>
              ) : (
                <>
                  <Play className="w-3.5 h-3.5 fill-white" />
                  <span>Auto-Play Full Lifecycle (9 Steps)</span>
                </>
              )}
            </button>

            <button
              onClick={() => advanceStep(currentStepIndex + 1)}
              disabled={isPlaying || currentStepIndex >= steps.length - 1}
              className="px-3.5 py-2 bg-white hover:bg-neutral-100 disabled:opacity-40 text-neutral-800 text-xs font-bold rounded-xl flex items-center space-x-1.5 transition border border-neutral-300 cursor-pointer shadow-xs"
            >
              <span>Next Step</span>
              <ChevronRight className="w-4 h-4 text-neutral-600" />
            </button>

            <button
              onClick={handleReset}
              className="p-2 bg-white hover:bg-neutral-100 text-neutral-600 hover:text-neutral-900 rounded-xl transition border border-neutral-300 cursor-pointer shadow-xs"
              title="Reset to Step 1"
            >
              <RotateCcw className="w-4 h-4" />
            </button>
          </div>

          <div className="flex items-center space-x-3">
            <div className="text-right">
              <div className="text-xs font-bold text-neutral-900">
                Step {currentStepIndex + 1} of {steps.length}: {currentStep.title}
              </div>
              <div className="text-[10px] text-neutral-500 font-mono">
                Overall Lifecycle Completion: {progressPercent}%
              </div>
            </div>
            <div className="w-28 h-3 bg-neutral-200 rounded-full overflow-hidden border border-neutral-300">
              <div 
                className="h-full bg-gradient-to-r from-amber-600 to-[#991b1b] transition-all duration-500"
                style={{ width: `${progressPercent}%` }}
              />
            </div>
          </div>
        </div>

        {/* BODY (2-Column: Step Pipeline + Active Inspector) */}
        <div className="flex-1 overflow-y-auto p-6 grid grid-cols-1 lg:grid-cols-12 gap-6">

          {/* LEFT COLUMN: 9-Step Interactive Timeline */}
          <div className="lg:col-span-5 space-y-2.5">
            <h3 className="text-xs font-bold uppercase tracking-wider text-neutral-500 mb-2 flex items-center gap-1.5">
              <Layers className="w-3.5 h-3.5" />
              Statutory Progression Pipeline
            </h3>

            <div className="space-y-2">
              {steps.map((step, idx) => {
                const Icon = step.icon;
                const isSelected = currentStepIndex === idx;
                const isDone = completedSteps.includes(idx);

                return (
                  <button
                    key={step.id}
                    onClick={() => {
                      setIsPlaying(false);
                      advanceStep(idx);
                    }}
                    className={`w-full text-left p-3 rounded-2xl border transition flex items-start space-x-3 cursor-pointer ${
                      isSelected 
                        ? 'bg-white border-[#991b1b] shadow-md ring-2 ring-[#991b1b]/10' 
                        : isDone 
                        ? 'bg-neutral-50/80 border-emerald-200 hover:bg-white' 
                        : 'bg-white border-neutral-200 hover:border-neutral-300 opacity-70'
                    }`}
                  >
                    <div className={`w-8 h-8 rounded-xl flex items-center justify-center shrink-0 border ${
                      isDone 
                        ? 'bg-emerald-600 text-white border-emerald-500' 
                        : isSelected 
                        ? step.colorClass 
                        : 'bg-neutral-100 text-neutral-500 border-neutral-200'
                    }`}>
                      {isDone && !isSelected ? (
                        <Check className="w-4 h-4" />
                      ) : (
                        <Icon className="w-4 h-4" />
                      )}
                    </div>

                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between">
                        <span className="text-[10px] font-mono font-bold text-neutral-500 uppercase">
                          Step {step.id} • {step.phase.split(':')[0]}
                        </span>
                        {isDone && (
                          <span className="text-[9px] font-bold text-emerald-700 bg-emerald-50 border border-emerald-200 px-1.5 py-0.2 rounded">
                            COMPLETED
                          </span>
                        )}
                      </div>
                      <div className="text-xs font-bold text-neutral-900 truncate">
                        {step.title}
                      </div>
                      <div className="text-[10px] text-neutral-500 truncate mt-0.5">
                        {step.statutoryLabel}
                      </div>
                    </div>
                  </button>
                );
              })}
            </div>
          </div>

          {/* RIGHT COLUMN: Active Step Inspector & Live Payload */}
          <div className="lg:col-span-7 space-y-4 flex flex-col justify-between">
            
            {/* Active Step Details Card */}
            <div className="p-5 bg-white border border-neutral-200 rounded-3xl space-y-4 shadow-sm">
              <div className="flex items-start justify-between gap-3">
                <div className="flex items-center space-x-3">
                  <div className={`w-11 h-11 rounded-2xl border flex items-center justify-center shadow-xs ${currentStep.colorClass}`}>
                    <currentStep.icon className="w-5 h-5" />
                  </div>
                  <div>
                    <span className="text-[10px] uppercase font-bold tracking-wider text-neutral-500 block">
                      {currentStep.phase}
                    </span>
                    <h3 className="text-base font-bold text-neutral-900">
                      Step {currentStep.id}: {currentStep.title}
                    </h3>
                  </div>
                </div>

                <span className="px-2.5 py-1 rounded-full text-xs font-bold bg-emerald-50 text-emerald-950 border border-emerald-300 flex items-center gap-1 shadow-2xs">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-700" />
                  Live Handshake 200 OK
                </span>
              </div>

              <p className="text-xs text-neutral-700 leading-relaxed bg-neutral-50 p-3.5 rounded-2xl border border-neutral-200">
                {currentStep.summary}
              </p>

              <div className="flex flex-wrap items-center justify-between gap-2 pt-1 text-[11px] font-semibold text-neutral-600">
                <div className="flex items-center space-x-1.5">
                  <ShieldCheck className="w-4 h-4 text-amber-700" />
                  <span>Statutory Compliance: <strong className="text-neutral-900">{currentStep.statutoryLabel}</strong></span>
                </div>

                <div className="flex items-center space-x-1.5 font-mono text-[10px]">
                  <span className="text-neutral-400">Gateway:</span>
                  <span className="text-neutral-800 bg-neutral-100 px-2 py-0.5 rounded border border-neutral-200">{currentStep.systemConnected}</span>
                </div>
              </div>

              {/* Action Toolbar for Step */}
              <div className="pt-2 border-t border-neutral-100 flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <button
                    onClick={() => {
                      onClose();
                      onLaunchModal?.(currentStep.launchKey, currentCase);
                    }}
                    className="px-3.5 py-2 bg-[#991b1b] hover:bg-red-800 text-white rounded-xl text-xs font-bold flex items-center space-x-1.5 transition cursor-pointer shadow-xs border border-amber-400/30"
                  >
                    <span>Launch {currentStep.title.split(' ')[0]} Console</span>
                    <ExternalLink className="w-3.5 h-3.5 text-amber-200" />
                  </button>
                </div>

                <button
                  onClick={copyPayload}
                  className="px-3 py-1.5 bg-neutral-100 hover:bg-neutral-200 text-neutral-700 rounded-xl text-xs font-bold flex items-center space-x-1.5 transition cursor-pointer border border-neutral-200"
                >
                  {copiedPayload ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedPayload ? 'Copied' : 'Copy Payload'}</span>
                </button>
              </div>
            </div>

            {/* Generated Data Payload Console */}
            <div className="bg-slate-950 p-4 rounded-3xl border border-slate-800 text-slate-300 space-y-2 flex-1 flex flex-col justify-between">
              <div className="flex items-center justify-between text-xs font-mono">
                <span className="text-amber-400 flex items-center gap-1.5 font-bold">
                  <Terminal className="w-3.5 h-3.5" />
                  {currentStep.payloadType} (Live System Output)
                </span>
                <span className="text-slate-500 text-[10px]">JSON / XML Stream</span>
              </div>

              <pre className="text-[11px] font-mono text-emerald-300 bg-slate-900 p-3.5 rounded-2xl overflow-x-auto max-h-48 border border-slate-800 flex-1">
                {currentStep.getPayload(currentCase)}
              </pre>
            </div>

          </div>

        </div>

        {/* FOOTER: REAL-TIME SIMULATION LOGS */}
        <div className="p-4 bg-neutral-900 border-t border-neutral-800 flex flex-wrap items-center justify-between gap-3 text-xs font-mono text-neutral-300 shrink-0">
          <div className="flex items-center space-x-2">
            <Clock className="w-4 h-4 text-amber-400" />
            <span className="text-amber-300 font-bold">Execution Stream:</span>
            <span className="text-neutral-400 truncate max-w-xl">
              {logs[0] || 'Ready to begin simulation.'}
            </span>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={() => advanceStep(currentStepIndex + 1)}
              disabled={currentStepIndex >= steps.length - 1}
              className="px-3 py-1 bg-neutral-800 hover:bg-neutral-700 disabled:opacity-40 text-amber-300 text-[11px] font-bold rounded-lg border border-neutral-700 flex items-center space-x-1 cursor-pointer"
            >
              <span>Advance Next</span>
              <ArrowRight className="w-3 h-3" />
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
